apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstpodrc
  labels:
    app: node
spec:
  replicas: 3
  template:
    metadata:
      name: myfirstpod
      labels:
        app: node
    spec:
      containers:
      - name: myfirstpod
        image: kalpana16/todoapp
        ports:
        - containerPort: 3000
